CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(128) NOT NULL UNIQUE,
    nickname VARCHAR(32) NOT NULL UNIQUE,
    provider VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);